// Generated by scripts/build-api.ts from functions/ai/analyze-report.ts - edit that file, then rebuild.

// src/core/ai/analyzeReport.ts
import { GoogleGenAI } from "@google/genai";

// src/core/ai/learnedProfile.ts
var norm = (s) => (s || "").trim().toLowerCase().replace(/[^a-z0-9.]/g, "");
var PROFILE_FIELDS = [
  "ticket",
  "pnr",
  "passenger",
  "date",
  "amount",
  "debit",
  "credit",
  "total",
  "commission",
  "status",
  "currency",
  "route",
  "req",
  "cabin"
];
function validateProfileDraft(draft, headers) {
  const errors = [];
  const warnings = [];
  const vendorName = typeof draft.vendorName === "string" ? draft.vendorName.trim() : "";
  if (!vendorName) errors.push("AI did not return a vendor name.");
  const rawCols = draft.columns && typeof draft.columns === "object" ? draft.columns : {};
  const normedHeaders = headers.map(norm);
  const columns = {};
  for (const field of PROFILE_FIELDS) {
    const value = rawCols[field];
    if (typeof value !== "string" || !value.trim()) continue;
    const idx = normedHeaders.indexOf(norm(value));
    if (idx === -1) {
      warnings.push(`Mapping for "${field}" points at header "${value}" which does not exist \u2014 dropped.`);
      continue;
    }
    columns[field] = headers[idx];
  }
  if (!columns.ticket && !columns.pnr) errors.push("No usable row identifier: neither a ticket nor a PNR column was mapped.");
  if (!columns.amount && !columns.debit && !columns.total) errors.push("No usable money column: neither amount, debit, nor total was mapped.");
  const rawRefund = draft.rules?.refund;
  const refund = rawRefund === "credit_column" || rawRefund === "status_column" || rawRefund === "negative_amount" ? rawRefund : columns.credit ? "credit_column" : columns.status ? "status_column" : "negative_amount";
  if (errors.length > 0) return { errors };
  return {
    profile: {
      vendorName,
      isLCC: draft.isLCC === true || !columns.ticket && !!columns.pnr,
      columns,
      rules: { refund }
    },
    warnings
  };
}

// src/core/ai/analyzeReport.ts
var PROMPT_INTRO = `You are the column-mapping brain of a travel-agency reconciliation ERP.
A new vendor report has arrived in a layout the system has never seen. Your job is
exactly what a human integrator does: work out which column holds which field, so
the report can be parsed deterministically forever after.

HOW TO DECIDE \u2014 judge a column by the SHAPE OF ITS VALUES first and its header
second. Headers lie: they get renamed, abbreviated, translated, left blank, or
duplicated. Values do not.

  ticket     13-15 digit document number, often written "123-4567890123" or
             "065 - 6905958893". The first 3 digits are the airline code.
             NOT the booking id, NOT the invoice number.
  pnr        record locator: 5-6 chars, letters+digits, e.g. "8SX9OF", "YB7LJY".
  passenger  a person's name, usually "SURNAME/GIVEN NAMES" or "GIVEN/SURNAME".
  date       the ISSUE / transaction date. If several date columns exist, pick
             the one for when the document was issued, NOT the travel/departure
             date and NOT the booking-created date.
  amount     ONE signed column where negative already means refund.
  debit      / credit \u2014 use this PAIR instead when the vendor keeps two columns.
  total      gross document value, when it is separate from the net.
  commission the agency's commission. Typically 0-20% of the total.
  status     the transaction-type word: issd/issue/TKTT, rfnd/rfndp/refund/RFND,
             void/CANX/CANN/RFNX, EMD, ADM, ACM.
  currency   3-letter code (AED, SAR, USD...).
  route      airport pairs: "JED-RUH", "RUH-LHR-RUH", "AHB/JED/MED/JED/AHB".
             MUST look like 3-letter airport codes joined by - or /.
  req        the AGENCY'S OWN internal request number, the thing they reconcile
             against. Looks like "SA 1109", "KSAML1331", "REQ 10333", "R-147".
             This is usually a column the agency ADDED to the vendor's export.

TRAPS THAT HAVE CAUSED REAL LOSSES HERE \u2014 check each one before answering:
  1. Do NOT map an invoice/LPO number ("INV-26-01-0565", "RFD-26-01-0347") to
     route. Those are references, not itineraries. If nothing looks like airport
     codes, return null for route.
  2. Do NOT map the vendor's own booking reference or file number to req. req is
     the agency's number. If two candidates exist, prefer the one whose values do
     NOT also appear in another column.
  3. Do NOT confuse tax with commission. If a column equals the tax column value
     for value, it is tax mislabelled \u2014 return null for commission rather than
     mapping it.
  4. Reports repeat columns (the PNR often appears twice, once near the start and
     once near the end). Map the FIRST occurrence.
  5. A column of "true/false", a username, an office id or an agency name is never
     one of these fields.

Also determine:
  vendorName    short human name for this vendor/format, from context in the data
                (an airline name, a carrier code, an agency/consolidator name).
  isLCC         true when the report has NO real ticket numbers and the PNR is the
                only row identifier.
  rules.refund  how a refund is expressed in THIS format:
                "negative_amount" \u2014 the amount column goes negative
                "credit_column"   \u2014 a separate credit column is filled
                "status_column"   \u2014 only the status word says so

Answer with the EXACT header text for each field, copied character for character
from the HEADERS list, or null when the format genuinely has no such column.
Never invent a header that is not in the list. Prefer null over a bad guess: a
wrong mapping silently corrupts the ledger, a null just means the field is empty.

Respond with ONLY valid JSON, no markdown fences, matching exactly:
{"vendorName": string, "isLCC": boolean, "columns": {${PROFILE_FIELDS.map((f) => `"${f}": string|null`).join(", ")}}, "rules": {"refund": string}}`;
function describeColumns(headers, sampleRows) {
  return headers.map((h, i) => {
    const seen = /* @__PURE__ */ new Set();
    for (const row of sampleRows) {
      const v = (row[i] ?? "").toString().trim();
      if (v && seen.size < 5) seen.add(v.slice(0, 40));
    }
    const samples = [...seen];
    const label = (h ?? "").toString().trim() || "(no header)";
    return `[${i}] "${label}" -> ${samples.length ? samples.map((s) => JSON.stringify(s)).join(", ") : "(always empty)"}`;
  }).join("\n");
}
async function analyzeReportWithAI(headers, sampleRows, apiKey) {
  const ai = new GoogleGenAI({ apiKey });
  const sample = sampleRows.slice(0, 15).map((r) => r.map((v) => (v ?? "").slice(0, 60)));
  const prompt = `${PROMPT_INTRO}

HEADERS (${headers.length} columns) \u2014 copy these EXACTLY when answering:
${JSON.stringify(headers)}

COLUMN BY COLUMN (header, then distinct values actually seen in that column):
${describeColumns(headers, sample)}

FULL SAMPLE ROWS, for cross-checking how the columns line up:
${sample.map((r) => JSON.stringify(r)).join("\n")}`;
  const model = process.env.GEMINI_MODEL || "gemini-flash-latest";
  let response;
  let lastErr;
  for (let attempt = 1; attempt <= 4; attempt++) {
    try {
      response = await ai.models.generateContent({
        model,
        contents: prompt,
        config: { responseMimeType: "application/json" }
      });
      break;
    } catch (err) {
      lastErr = err;
      const msg = err instanceof Error ? err.message : String(err);
      if (!/503|UNAVAILABLE|overloaded|high demand|429/i.test(msg) || attempt === 4) throw err;
      await new Promise((r) => setTimeout(r, attempt * 2e3));
    }
  }
  if (!response) throw lastErr instanceof Error ? lastErr : new Error(String(lastErr));
  const text = (response.text ?? "").trim().replace(/^```json?\s*/i, "").replace(/```\s*$/, "");
  let draft;
  try {
    draft = JSON.parse(text);
  } catch {
    throw new Error(`AI returned unparseable output: ${text.slice(0, 200)}`);
  }
  const validated = validateProfileDraft(draft, headers);
  if ("errors" in validated) {
    throw new Error(`AI mapping rejected: ${validated.errors.join(" \xB7 ")}`);
  }
  return { ...validated.profile, aiWarnings: validated.warnings };
}

// functions/ai/analyze-report.ts
async function handler(req, res) {
  if (req.method !== "POST") {
    res.status(405).json({ error: "Method not allowed" });
    return;
  }
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    res.status(500).json({ error: "GEMINI_API_KEY is not configured on the server" });
    return;
  }
  const { headers, sampleRows } = req.body ?? {};
  if (!Array.isArray(headers) || headers.length === 0 || !Array.isArray(sampleRows)) {
    res.status(400).json({ error: "Body must be { headers: string[], sampleRows: string[][] }" });
    return;
  }
  try {
    const result = await analyzeReportWithAI(headers, sampleRows, apiKey);
    res.status(200).json(result);
  } catch (err) {
    console.error(err);
    const message = err instanceof Error ? err.message : String(err);
    res.status(500).json({ error: message });
  }
}
export {
  handler as default
};
