/**
 * Bundle the serverless functions into api/.
 *
 * The project is "type": "module", and Vercel runs a file under api/ as it
 * stands: an import with no extension - every import in src/ - fails at
 * load, which is how /api/ai/analyze-report answered every call with
 * FUNCTION_INVOCATION_FAILED. So each function is written in functions/ and
 * bundled here into one file with everything of ours inlined; packages stay
 * imports, installed on Vercel as usual.
 *
 *   npx tsx scripts/build-api.ts            (write api/)
 *   npx tsx scripts/build-api.ts --check    (fail if api/ is not what functions/ builds)
 */
import { build } from 'esbuild';
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { dirname } from 'path';

export const FUNCTIONS: Record<string, string> = {
  'api/airtable/sync.js': 'functions/airtable/sync.ts',
  'api/ai/analyze-report.js': 'functions/ai/analyze-report.ts',
};

export async function bundle(entry: string): Promise<string> {
  const r = await build({
    entryPoints: [entry], bundle: true, platform: 'node', format: 'esm', target: 'node20',
    packages: 'external', write: false, legalComments: 'none', logLevel: 'silent',
    banner: { js: `// Generated by scripts/build-api.ts from ${entry} - edit that file, then rebuild.` },
  });
  return r.outputFiles[0].text;
}

(async () => {
  const check = process.argv.includes('--check');
  let stale = 0;
  for (const [out, entry] of Object.entries(FUNCTIONS)) {
    const js = await bundle(entry);
    if (check) {
      const same = existsSync(out) && readFileSync(out, 'utf8').replace(/\r\n/g, '\n') === js.replace(/\r\n/g, '\n');
      console.log(`  ${same ? 'PASS' : 'FAIL'}  ${out} is what ${entry} builds`);
      if (!same) stale++;
    } else {
      mkdirSync(dirname(out), { recursive: true });
      writeFileSync(out, js);
      console.log(`wrote ${out} (${(js.length / 1024).toFixed(0)} KB)`);
    }
  }
  if (check) { console.log(`\n${Object.keys(FUNCTIONS).length - stale} passed, ${stale} failed`); process.exit(stale ? 1 : 0); }
})();
