-- 0001 core schema: vendors registry + per-vendor row provenance
-- Every ticket/report row in a vendor_*_rows table is a copy of an Excel row from the
-- canonical Aviation seed workbook. Reports are built on top of these raw rows later.

set search_path = public;

create table if not exists vendors (
  slug         text primary key,
  display_name text not null,
  sheet_name   text not null,
  seed_rows    integer not null default 0
);

create table if not exists vendor_columns (
  vendor_slug   text not null references vendors(slug) on delete cascade,
  ordinal       integer not null,
  sql_name      text not null,
  original      text not null,
  primary key (vendor_slug, ordinal)
);

create table if not exists vendor_imports (
  id             uuid primary key default gen_random_uuid(),
  vendor_slug    text not null references vendors(slug),
  source_file    text not null,
  imported_at    timestamptz not null default now(),
  imported_by    text,
  row_count      integer not null default 0
);

-- Seed vendors
insert into vendors (slug, display_name, sheet_name, seed_rows) values
  ('iata', 'IATA', 'IATA', 1568),
  ('flydubai', 'FlyDubai', 'FLYDubai', 27),
  ('flyadeal_dxb', 'FlyAdeal DXB', 'FlyAdeal DXB', 90),
  ('flyadeal_ksa', 'FlyAdeal KSA', 'FlyAdeal KSA', 4),
  ('airarabia', 'Air Arabia', 'Air Arabia ', 18),
  ('flynas', 'Flynas', 'FlyNas', 19),
  ('rts_ibtekar', 'RTS Ibtekar', 'RTS IBTKAR ', 8),
  ('ibtekar', 'Ibtekar', 'ibtekar', 265),
  ('rts_dxb', 'RTS DXB', 'RTS DXB', 249),
  ('nsa', 'NSA', 'NSA', 2785),
  ('goldmedal', 'Gold Medal', 'goldmedal', 6)
on conflict (slug) do update set
  display_name = excluded.display_name,
  sheet_name = excluded.sheet_name,
  seed_rows = excluded.seed_rows;

-- Seed vendor_columns (verbatim original header preserved)
insert into vendor_columns (vendor_slug, ordinal, sql_name, original) values
  ('iata', 1, 'col_1', ''),
  ('iata', 2, 'serial', 'Serial '),
  ('iata', 3, 'airline_key', 'Airline key'),
  ('iata', 4, 'ticket_number', 'ticket number '),
  ('iata', 5, 'total', 'total '),
  ('iata', 6, 'tax', 'tax '),
  ('iata', 7, 'comm', 'comm'),
  ('iata', 8, 'net', 'NET'),
  ('iata', 9, 'pax_name', 'Pax Name '),
  ('iata', 10, 'pnr', 'PNR '),
  ('iata', 11, 'service', 'Service '),
  ('iata', 12, 'req_number', 'Req Number '),
  ('flydubai', 1, 'invoice_no', 'Invoice no.'),
  ('flydubai', 2, 'payment_date', 'Payment date'),
  ('flydubai', 3, 'booking_reference', 'Booking reference'),
  ('flydubai', 4, 'master_booking_reference', 'Master booking reference'),
  ('flydubai', 5, 'agency', 'Agency'),
  ('flydubai', 6, 'user_id', 'User ID'),
  ('flydubai', 7, 'amount', 'Amount'),
  ('flydubai', 8, 'deposit_date', 'Deposit date'),
  ('flydubai', 9, 'balance', 'Balance'),
  ('flydubai', 10, 'balance_due', 'Balance due'),
  ('flydubai', 11, 'payment_reference', 'Payment reference'),
  ('flydubai', 12, 'payer_id', 'Payer ID'),
  ('flydubai', 13, 'total_passengers', 'Total passengers'),
  ('flydubai', 14, 'total_segments', 'Total segments'),
  ('flydubai', 15, 'order_no', 'Order no.'),
  ('flydubai', 16, 'passenger_name', 'Passenger name'),
  ('flydubai', 17, 'departure_date', 'Departure date'),
  ('flydubai', 18, 'booked_date', 'Booked date'),
  ('flydubai', 19, 'remarks', 'Remarks'),
  ('flydubai', 20, 'currency_code', 'Currency Code'),
  ('flydubai', 21, 'req_number', 'REQ Number '),
  ('flydubai', 22, 'status', 'Status'),
  ('flyadeal_dxb', 1, 'paymentdate', 'paymentDate'),
  ('flyadeal_dxb', 2, 'pnr', 'pnr'),
  ('flyadeal_dxb', 3, 'parentorganizationcode', 'parentOrganizationCode'),
  ('flyadeal_dxb', 4, 'organizationcode', 'organizationCode'),
  ('flyadeal_dxb', 5, 'type', 'type'),
  ('flyadeal_dxb', 6, 'passenger_name', 'passenger_Name'),
  ('flyadeal_dxb', 7, 'emailaddress', 'emailAddress'),
  ('flyadeal_dxb', 8, 'phone', 'phone'),
  ('flyadeal_dxb', 9, 'bookingamount', 'bookingAmount'),
  ('flyadeal_dxb', 10, 'bookingcurrency', 'bookingCurrency'),
  ('flyadeal_dxb', 11, 'accountamount', 'accountAmount'),
  ('flyadeal_dxb', 12, 'accountcurrency', 'accountCurrency'),
  ('flyadeal_dxb', 13, 'balance', 'Balance '),
  ('flyadeal_dxb', 14, 'promocode', 'promoCode'),
  ('flyadeal_dxb', 15, 'segmentcount', 'segmentCount'),
  ('flyadeal_dxb', 16, 'sourceusercode', 'sourceUsercode'),
  ('flyadeal_dxb', 17, 'req_number', 'Req number '),
  ('flyadeal_dxb', 18, 'column1', 'Column1'),
  ('flyadeal_dxb', 19, 'col_19', ''),
  ('flyadeal_dxb', 20, 'col_20', ''),
  ('flyadeal_dxb', 21, 'status', 'Status'),
  ('flyadeal_ksa', 1, 'createdusercode', 'createdUserCode'),
  ('flyadeal_ksa', 2, 'organizationcode', 'organizationCode'),
  ('flyadeal_ksa', 3, 'parentorganizationcode', 'parentorganizationcode'),
  ('flyadeal_ksa', 4, 'recordlocator', 'recordLocator'),
  ('flyadeal_ksa', 5, 'seat', 'seat'),
  ('flyadeal_ksa', 6, 'seatamount', 'seatamount'),
  ('flyadeal_ksa', 7, 'inft', 'inft'),
  ('flyadeal_ksa', 8, 'passengername', 'passengerName'),
  ('flyadeal_ksa', 9, 'emailaddress', 'emailAddress'),
  ('flyadeal_ksa', 10, 'phone', 'phone'),
  ('flyadeal_ksa', 11, 'flightnumber', 'flightNumber'),
  ('flyadeal_ksa', 12, 'departuredate', 'departureDate'),
  ('flyadeal_ksa', 13, 'legdetails', 'legDetails'),
  ('flyadeal_ksa', 14, 'pnrtotal', 'pnrTotal'),
  ('flyadeal_ksa', 15, 'baseyq', 'baseyq'),
  ('flyadeal_ksa', 16, 'basefare', 'baseFare'),
  ('flyadeal_ksa', 17, 'ssrfees', 'ssrFees'),
  ('flyadeal_ksa', 18, 'cmf', 'cmf'),
  ('flyadeal_ksa', 19, 'othercharge', 'otherCharge'),
  ('flyadeal_ksa', 20, 'promotiondiscount', 'promotionDiscount'),
  ('flyadeal_ksa', 21, 'discount', 'discount'),
  ('flyadeal_ksa', 22, 'pnrcurrency', 'pnrCurrency'),
  ('flyadeal_ksa', 23, 'totalinorgcurrency', 'totalInOrgCurrency'),
  ('flyadeal_ksa', 24, 'status', 'status'),
  ('flyadeal_ksa', 25, 'paxstatus', 'paxStatus'),
  ('flyadeal_ksa', 26, 'organizationcurrency', 'organizationCurrency'),
  ('flyadeal_ksa', 27, 'abca', 'abca'),
  ('flyadeal_ksa', 28, 'abcd', 'abcd'),
  ('flyadeal_ksa', 29, 'ae', 'ae'),
  ('flyadeal_ksa', 30, 'chng', 'chng'),
  ('flyadeal_ksa', 31, 'd9', 'd9'),
  ('flyadeal_ksa', 32, 'e3', 'e3'),
  ('flyadeal_ksa', 33, 'eg', 'eg'),
  ('flyadeal_ksa', 34, 'eq', 'eq'),
  ('flyadeal_ksa', 35, 'exbg', 'exbg'),
  ('flyadeal_ksa', 36, 'f25', 'f25'),
  ('flyadeal_ksa', 37, 'f6', 'f6'),
  ('flyadeal_ksa', 38, 'f7', 'f7'),
  ('flyadeal_ksa', 39, 'fare', 'fare'),
  ('flyadeal_ksa', 40, 'gz', 'gz'),
  ('flyadeal_ksa', 41, 'hq', 'hq'),
  ('flyadeal_ksa', 42, 'io', 'io'),
  ('flyadeal_ksa', 43, 'jk', 'jk'),
  ('flyadeal_ksa', 44, 'k7', 'k7'),
  ('flyadeal_ksa', 45, 'balamce', 'Balamce'),
  ('flyadeal_ksa', 46, 'req_number', 'Req Number '),
  ('airarabia', 1, 'reference_code', 'Reference Code'),
  ('airarabia', 2, 'transaction_date', 'Transaction date'),
  ('airarabia', 3, 'debit_amount', 'Debit Amount'),
  ('airarabia', 4, 'credit_amount', 'Credit Amount'),
  ('airarabia', 5, 'balance', 'balance '),
  ('airarabia', 6, 'remarks', 'Remarks'),
  ('airarabia', 7, 'ticket_number', 'Ticket Number '),
  ('airarabia', 8, 'custmoner_name', 'Custmoner name '),
  ('airarabia', 9, 'user_id', 'User ID'),
  ('airarabia', 10, 'request_number', 'Request Number '),
  ('airarabia', 11, 'column2', 'Column2'),
  ('airarabia', 12, 'status', 'Status '),
  ('flynas', 1, 'date', 'Date'),
  ('flynas', 2, 'pnr2', 'PNR2'),
  ('flynas', 3, 'pax', 'pax '),
  ('flynas', 4, 'amount', 'AMOUNT'),
  ('flynas', 5, 'req_number', 'REQ. NUMBER '),
  ('flynas', 6, 'balance', 'balance '),
  ('flynas', 7, 'column6', 'Column6'),
  ('flynas', 8, 'status', 'Status '),
  ('rts_ibtekar', 1, 'col_1', ''),
  ('rts_ibtekar', 2, 'pnr_creation_date', 'PNR creation date'),
  ('rts_ibtekar', 3, 'record_locator', 'Record Locator'),
  ('rts_ibtekar', 4, 'officeid_bk', 'OfficeId Bk'),
  ('rts_ibtekar', 5, 'officeid_tk', 'OfficeId Tk'),
  ('rts_ibtekar', 6, 'signinbooking', 'SignInBooking'),
  ('rts_ibtekar', 7, 'signinticketing', 'SignInTicketing'),
  ('rts_ibtekar', 8, 'passenger', 'Passenger'),
  ('rts_ibtekar', 9, 'paxtype', 'PaxType'),
  ('rts_ibtekar', 10, 'depdate', 'DepDate'),
  ('rts_ibtekar', 11, 'arrdate', 'ArrDate'),
  ('rts_ibtekar', 12, 'numberofsegments', 'NumberOfSegments'),
  ('rts_ibtekar', 13, 'fare_basis_es', 'Fare basis(es)'),
  ('rts_ibtekar', 14, 'booking_class_es', 'Booking class(es)'),
  ('rts_ibtekar', 15, 'service_class_es', 'Service class(es)'),
  ('rts_ibtekar', 16, 'route', 'Route'),
  ('rts_ibtekar', 17, 'flight_numbers', 'Flight numbers'),
  ('rts_ibtekar', 18, 'baggage', 'Baggage'),
  ('rts_ibtekar', 19, 'date', 'Date'),
  ('rts_ibtekar', 20, 'no', 'No'),
  ('rts_ibtekar', 21, 'carrier', 'Carrier'),
  ('rts_ibtekar', 22, 'type', 'Type'),
  ('rts_ibtekar', 23, 'action', 'Action'),
  ('rts_ibtekar', 24, 'issue_type', 'Issue type'),
  ('rts_ibtekar', 25, 'fare', 'Fare'),
  ('rts_ibtekar', 26, 'fare_currency', 'Fare currency'),
  ('rts_ibtekar', 27, 'net_fare', 'Net fare'),
  ('rts_ibtekar', 28, 'fare_equiv', 'Fare equiv'),
  ('rts_ibtekar', 29, 'fare_equiv_currency', 'Fare equiv. currency'),
  ('rts_ibtekar', 30, 'commission', 'Commission'),
  ('rts_ibtekar', 31, 'commission_equiv', 'Commission equiv'),
  ('rts_ibtekar', 32, 'taxes', 'Taxes'),
  ('rts_ibtekar', 33, 'taxes_currency', 'Taxes currency'),
  ('rts_ibtekar', 34, 'sfdiscount', 'SFDiscount'),
  ('rts_ibtekar', 35, 'hf', 'HF'),
  ('rts_ibtekar', 36, 'service_fee', 'Service fee'),
  ('rts_ibtekar', 37, 'sftotal', 'SfTotal'),
  ('rts_ibtekar', 38, 'markuptotal', 'MarkUpTotal'),
  ('rts_ibtekar', 39, 'markupvat', 'MarkUpVat'),
  ('rts_ibtekar', 40, 'markupdiscount', 'MarkUpDiscount'),
  ('rts_ibtekar', 41, 'service_fee_vat', 'Service fee VAT'),
  ('rts_ibtekar', 42, 'total', 'Total'),
  ('rts_ibtekar', 43, 'total_currency', 'Total currency'),
  ('rts_ibtekar', 44, 'national_total', 'National total'),
  ('rts_ibtekar', 45, 'national_currency', 'National currency'),
  ('rts_ibtekar', 46, 'misc_fees', 'Misc. fees'),
  ('rts_ibtekar', 47, 'grand_total', 'Grand total'),
  ('rts_ibtekar', 48, 'currency_rate', 'Currency rate'),
  ('rts_ibtekar', 49, 'fop', 'FOP'),
  ('rts_ibtekar', 50, 'document_credit_total', 'Document credit total'),
  ('rts_ibtekar', 51, 'sf_credit_total', 'SF credit total'),
  ('rts_ibtekar', 52, 'credit_currency', 'Credit currency'),
  ('rts_ibtekar', 53, 'credit_currency_rate', 'Credit currency rate'),
  ('rts_ibtekar', 54, 'booking_terminal_id', 'Booking terminal ID'),
  ('rts_ibtekar', 55, 'ticketing_terminal_id', 'Ticketing terminal ID'),
  ('ibtekar', 1, 'date', 'Date'),
  ('ibtekar', 2, 'file_no', 'File No'),
  ('ibtekar', 3, 'doc_no', 'Doc No'),
  ('ibtekar', 4, 'col_4', ''),
  ('ibtekar', 5, 'ticket', 'Ticket'),
  ('ibtekar', 6, 'pnr', 'PNR'),
  ('ibtekar', 7, 'issue_date', 'Issue Date'),
  ('ibtekar', 8, 'lpo_no', 'LPO No'),
  ('ibtekar', 9, 'passenger', 'Passenger'),
  ('ibtekar', 10, 'sector', 'Sector'),
  ('ibtekar', 11, 'debit', 'Debit'),
  ('ibtekar', 12, 'credit', 'Credit'),
  ('ibtekar', 13, 'balance', 'Balance'),
  ('ibtekar', 14, 'travel_date', 'Travel Date'),
  ('ibtekar', 15, 'return_date', 'Return Date'),
  ('ibtekar', 16, 'status', 'Status'),
  ('ibtekar', 17, 'col_17', ''),
  ('ibtekar', 18, 'mm', 'MM'),
  ('rts_dxb', 1, 'pnr_creation_date', 'PNR creation date'),
  ('rts_dxb', 2, 'record_locator', 'Record Locator'),
  ('rts_dxb', 3, 'passenger', 'Passenger'),
  ('rts_dxb', 4, 'no', 'No'),
  ('rts_dxb', 5, 'col_5', ''),
  ('rts_dxb', 6, 'action', 'Action'),
  ('rts_dxb', 7, 'total', 'Total'),
  ('rts_dxb', 8, 'total_currency', 'Total currency'),
  ('rts_dxb', 9, 'national_total', 'National total'),
  ('rts_dxb', 10, 'national_currency', 'National currency'),
  ('rts_dxb', 11, 'misc_fees', 'Misc. fees'),
  ('rts_dxb', 12, 'grand_total', 'Grand total'),
  ('rts_dxb', 13, 'currency_rate', 'Currency rate'),
  ('rts_dxb', 14, 'fop', 'FOP'),
  ('rts_dxb', 15, 'document_credit_total', 'Document credit total'),
  ('rts_dxb', 16, 'sf_credit_total', 'SF credit total'),
  ('rts_dxb', 17, 'credit_currency', 'Credit currency'),
  ('rts_dxb', 18, 'credit_currency_rate', 'Credit currency rate'),
  ('rts_dxb', 19, 'booking_terminal_id', 'Booking terminal ID'),
  ('rts_dxb', 20, 'ticketing_terminal_id', 'Ticketing terminal ID'),
  ('nsa', 1, 'date', 'DATE'),
  ('nsa', 2, 'notes', 'notes'),
  ('nsa', 3, 'event_month', 'EVENT MONTH'),
  ('nsa', 4, 'lpo_number', 'LPO NUMBER'),
  ('nsa', 5, 'operator_name', 'Operator name '),
  ('nsa', 6, 'request_number', 'Request Number'),
  ('nsa', 7, 'doc_no', 'Doc No'),
  ('nsa', 8, 'description', 'Description'),
  ('nsa', 9, 'pnr', 'PNR'),
  ('nsa', 10, 'debit_sar', 'DEBIT (SAR)'),
  ('nsa', 11, 'credit_sar', 'Credit (SAR)'),
  ('nsa', 12, 'c_0utstanding_balances', '0utstanding balances'),
  ('nsa', 13, 'col_13', ''),
  ('nsa', 14, 'event_date', 'Event date '),
  ('nsa', 15, 'reason_for_pending', 'Reason For pending  '),
  ('goldmedal', 1, 'customer_no', 'Customer No'),
  ('goldmedal', 2, 'name', 'Name'),
  ('goldmedal', 3, 'transaction_type', 'Transaction_Type'),
  ('goldmedal', 4, 'invoice_number', 'Invoice Number'),
  ('goldmedal', 5, 'invoice_date', 'Invoice Date'),
  ('goldmedal', 6, 'col_6', ''),
  ('goldmedal', 7, 'passenger_name', 'Passenger Name'),
  ('goldmedal', 8, 'po_number', 'PO Number'),
  ('goldmedal', 9, 'curr', 'Curr'),
  ('goldmedal', 10, 'original_amount', 'Original Amount'),
  ('goldmedal', 11, 'balance_due', 'Balance Due'),
  ('goldmedal', 12, 'status', 'Status'),
  ('goldmedal', 13, 'routing', 'Routing'),
  ('goldmedal', 14, 'ticket_number', 'Ticket Number')
on conflict (vendor_slug, ordinal) do update set
  sql_name = excluded.sql_name,
  original = excluded.original;
