-- 0005 flyadeal_ksa_rows: verbatim copy of the "FlyAdeal KSA" sheet from Aviation seed workbook
-- 4 data rows in the canonical seed.

create table if not exists flyadeal_ksa_rows (
  id             uuid primary key default gen_random_uuid(),
  vendor_import_id uuid references vendor_imports(id) on delete set null,
  source_row_num integer not null,
  createdusercode                  text,
  organizationcode                 text,
  parentorganizationcode           text,
  recordlocator                    text,
  seat                             text,
  seatamount                       text,
  inft                             text,
  passengername                    text,
  emailaddress                     text,
  phone                            text,
  flightnumber                     text,
  departuredate                    text,
  legdetails                       text,
  pnrtotal                         text,
  baseyq                           text,
  basefare                         text,
  ssrfees                          text,
  cmf                              text,
  othercharge                      text,
  promotiondiscount                text,
  discount                         text,
  pnrcurrency                      text,
  totalinorgcurrency               text,
  status                           text,
  paxstatus                        text,
  organizationcurrency             text,
  abca                             text,
  abcd                             text,
  ae                               text,
  chng                             text,
  d9                               text,
  e3                               text,
  eg                               text,
  eq                               text,
  exbg                             text,
  f25                              text,
  f6                               text,
  f7                               text,
  fare                             text,
  gz                               text,
  hq                               text,
  io                               text,
  jk                               text,
  k7                               text,
  balamce                          text,
  req_number                       text,
  created_at     timestamptz not null default now()
);

create index if not exists flyadeal_ksa_rows_source_row_num_idx on flyadeal_ksa_rows(source_row_num);
create index if not exists flyadeal_ksa_rows_vendor_import_id_idx on flyadeal_ksa_rows(vendor_import_id);
