-- 0008 rts_ibtekar_rows: verbatim copy of the "RTS IBTKAR " sheet from Aviation seed workbook
-- 8 data rows in the canonical seed.

create table if not exists rts_ibtekar_rows (
  id             uuid primary key default gen_random_uuid(),
  vendor_import_id uuid references vendor_imports(id) on delete set null,
  source_row_num integer not null,
  col_1                            text,
  pnr_creation_date                text,
  record_locator                   text,
  officeid_bk                      text,
  officeid_tk                      text,
  signinbooking                    text,
  signinticketing                  text,
  passenger                        text,
  paxtype                          text,
  depdate                          text,
  arrdate                          text,
  numberofsegments                 text,
  fare_basis_es                    text,
  booking_class_es                 text,
  service_class_es                 text,
  route                            text,
  flight_numbers                   text,
  baggage                          text,
  date                             text,
  no                               text,
  carrier                          text,
  type                             text,
  action                           text,
  issue_type                       text,
  fare                             text,
  fare_currency                    text,
  net_fare                         text,
  fare_equiv                       text,
  fare_equiv_currency              text,
  commission                       text,
  commission_equiv                 text,
  taxes                            text,
  taxes_currency                   text,
  sfdiscount                       text,
  hf                               text,
  service_fee                      text,
  sftotal                          text,
  markuptotal                      text,
  markupvat                        text,
  markupdiscount                   text,
  service_fee_vat                  text,
  total                            text,
  total_currency                   text,
  national_total                   text,
  national_currency                text,
  misc_fees                        text,
  grand_total                      text,
  currency_rate                    text,
  fop                              text,
  document_credit_total            text,
  sf_credit_total                  text,
  credit_currency                  text,
  credit_currency_rate             text,
  booking_terminal_id              text,
  ticketing_terminal_id            text,
  created_at     timestamptz not null default now()
);

create index if not exists rts_ibtekar_rows_source_row_num_idx on rts_ibtekar_rows(source_row_num);
create index if not exists rts_ibtekar_rows_vendor_import_id_idx on rts_ibtekar_rows(vendor_import_id);
